buildscript {
  ext.kotlin_version = '2.1.0'

    ext {
        //HDFC PAYMENT
        clientId = "hdfcmaster"
        hyperSDKVersion = "2.1.32"
        excludedMicroSDKs = []
    }

}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = '../build'

subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}

subprojects {
    def configureAndroid = { p ->
        if (p.hasProperty('android')) {
            p.android {
                if (namespace == null) {
                    namespace p.group
                }
                compileSdkVersion 36
                defaultConfig {
                    targetSdkVersion 34
                }
            }
        }
    }

    if (project.state.executed) {
        configureAndroid(project)
    } else {
        project.afterEvaluate { p ->
            configureAndroid(p)
        }
    }
}

subprojects {
    project.evaluationDependsOn(':app')
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}