// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRP1RbSfNx17ZlbM-_JJyXPrT9_4xH0uM',
    appId: '1:28531733514:android:10a663dc8ee8a6e005dbf3',
    messagingSenderId: '28531733514',
    projectId: 'trackbox-3bbc7',
    storageBucket: 'trackbox-3bbc7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoNrlaBOlf1svvQHVhsJfvZHTqAcmWURQ',
    appId: '1:28531733514:ios:17740c204146d68705dbf3',
    messagingSenderId: '28531733514',
    projectId: 'trackbox-3bbc7',
    storageBucket: 'trackbox-3bbc7.firebasestorage.app',
    iosClientId:
        '28531733514-ak74dd28l9m81tqsn1mg60g6nsu730o4.apps.googleusercontent.com',
    iosBundleId: 'com.trackbox.student.RunnerTest',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjSZ9ANRY8baqvQVHnB5aDxiEU1H7bQdg',
    appId: '1:28531733514:web:904da5936ccbb3b105dbf3',
    messagingSenderId: '28531733514',
    projectId: 'trackbox-3bbc7',
    authDomain: 'trackbox-3bbc7.firebaseapp.com',
    storageBucket: 'trackbox-3bbc7.firebasestorage.app',
    measurementId: 'G-XTZ2FT7873',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRIyki-v8FYuS_IwKPWFDfVu8L-eX57oA',
    appId: '1:743674418055:web:961d66c1927fdff4077922',
    messagingSenderId: '743674418055',
    projectId: 'breffini-app',
    authDomain: 'breffini-app.firebaseapp.com',
    storageBucket: 'breffini-app.appspot.com',
    measurementId: 'G-F0SYN95QVG',
  );
}
